{pkgs}: let
  lib = pkgs.lib;
  stdenvNoCC = pkgs.stdenvNoCC;

  luaModuleList = with pkgs.luajitPackages; [
    {
      name = "plenary";
      path = plenary-nvim;
    }
    {
      name = "lua-utils"; # TODO: find a clean approach for lua module deps (luarocks adapter?)
      path = lua-utils-nvim;
    }
    {
      name = "jsregexp";
      path = jsregexp;
    }
    {
      name = "commons";
      path = commons-nvim;
    }
    {
      name = "pathlib";
      path = pathlib-nvim;
    }
    {
      name = "nui";
      path = nui-nvim;
    }
    {
      name = "nio";
      path = nvim-nio;
    }
  ];

  moduleMeta =
    map (p: {
      name = p.name;
      path = "${p.path}";
      rev = p.path.src.rev or "unknown";
      version = p.path.version or "unknown";
    })
    luaModuleList;

  jsonFile = builtins.toJSON (
    builtins.listToAttrs (map (m: {
        name = m.name;
        value = {
          inherit (m) name path rev version;
        };
      })
      moduleMeta)
  );

  luaFile =
    ''
      -- Auto-generated by Nix, do not edit.
      return {
    ''
    + pkgs.lib.concatMapStrings (m: ''
      ["${m.name}"] = {
        path    = "${m.path}",
        rev     = "${m.rev}",
        version = "${m.version}",
      },
    '')
    moduleMeta
    + ''
      }
    '';
in {
  # TODO
  OLD_luaModules = pkgs.runCommand "lua-modules" {} ''
    mkdir -p $out/pack/bundle/opt
    cp -rL ${pkgs.linkFarm "lua-modules" luaModuleList}/. $out/
    chmod -R u+w $out

    mkdir -p $out/meta

    cat > $out/meta/module_paths.lua << 'EOF'
    ${luaFile}
    EOF
    ${pkgs.stylua}/bin/stylua $out/meta/module_paths.lua

    cat > $out/meta/module_paths.json << 'EOF'
    ${jsonFile}
    EOF
    ${pkgs.python3}/bin/python3 -m json.tool --indent 4 $out/meta/module_paths.json \
      > $out/meta/tmp.json
    mv $out/meta/tmp.json $out/meta/module_paths.json

  '';

  luaModules = pkgs.symlinkJoin {
    name = "lua-modules";
    paths = map (x: x.path) luaModuleList;
    postBuild = ''
      mkdir -p $out/meta
      cat > $out/meta/module_paths.lua << 'EOF'
      ${luaFile}
      EOF
      ${pkgs.stylua}/bin/stylua $out/meta/module_paths.lua

      cat > $out/meta/module_paths.json << 'EOF'
      ${jsonFile}
      EOF
      ${pkgs.python3}/bin/python3 -m json.tool --indent 4 $out/meta/module_paths.json \
        > $out/meta/tmp.json
      mv $out/meta/tmp.json $out/meta/module_paths.json
    '';
  };
}
