{pkgs}: let
  lib = pkgs.lib;
  stdenvNoCC = pkgs.stdenvNoCC;

  inherit (import ./plugin-set.nix {inherit pkgs;}) nixpkgsList customList;

  fullList = customList ++ nixpkgsList;

  pluginMeta =
    map (p: {
      name = p.name;
      path = "${p.path}";
      rev = p.path.src.rev or "unknown";
      version = p.path.version or "unknown";
    })
    fullList;

  jsonFile = builtins.toJSON (
    builtins.listToAttrs (map (m: {
        name = m.name;
        value = {
          inherit (m) name path rev version;
        };
      })
      pluginMeta)
  );

  luaFile =
    ''
      -- Auto-generated by Nix, do not edit.
      return {
    ''
    + pkgs.lib.concatMapStrings (m: ''
      ["${m.name}"] = {
        path    = "${m.path}",
        rev     = "${m.rev}",
        version = "${m.version}",
      },
    '')
    pluginMeta
    + ''
      }
    '';
in {
  OLD_nvimPlugins = pkgs.runCommand "nvim-plugins" {} ''
    mkdir -p $out
    mkdir -p $out/plugins
    cp -rL ${pkgs.linkFarm "nvim-plugins" fullList}/. $out/plugins
    chmod -R u+w $out

    # Add meta files
    mkdir -p $out/meta

    cat > $out/meta/plugin_paths.lua << 'EOF'
    ${luaFile}
    EOF

    ${pkgs.stylua}/bin/stylua $out/meta/plugin_paths.lua

    cat > $out/meta/plugin_paths.json << 'EOF'
    ${jsonFile}
    EOF

    ${pkgs.python3}/bin/python3 -m json.tool --indent 4 $out/meta/plugin_paths.json > $out/meta/tmp.json
    mv $out/meta/tmp.json $out/meta/plugin_paths.json
  '';

  nvimPlugins = pkgs.runCommand "nvim-plugins" {} ''
    mkdir -p $out/pack/bundle/opt
    cp -rL ${pkgs.linkFarm "nvim-plugins" fullList}/. $out/pack/bundle/opt
    chmod -R u+w $out

    mkdir -p $out/meta

    cat > $out/meta/plugin_paths.lua << 'EOF'
    ${luaFile}
    EOF
    ${pkgs.stylua}/bin/stylua $out/meta/plugin_paths.lua

    cat > $out/meta/plugin_paths.json << 'EOF'
    ${jsonFile}
    EOF
    ${pkgs.python3}/bin/python3 -m json.tool --indent 4 $out/meta/plugin_paths.json \
      > $out/meta/tmp.json
    mv $out/meta/tmp.json $out/meta/plugin_paths.json

    # fix dial path so nvim can find it
    cp $out/pack/bundle/opt/dial/plugin/dial.lua $out/pack/bundle/opt/dial/lua/dial/init.lua
  '';

  standardPathsDerivation = stdenvNoCC.mkDerivation {
    name = "neovim-opt-pack";

    dontUnpack = true;
    dontConfigure = true;
    dontBuild = true;

    installPhase = ''
      runHook preInstall

      mkdir -p $out/pack/nix/opt

      ${lib.concatMapStrings (plugin: plugin: ''
          ln -s ${plugin.path} $out/pack/nix/opt/${plugin.name}
        '')
        fullList}

      runHook postInstall
    '';

    # passthru = {inherit plugins;};

    meta.description = "Neovim opt-pack: plugins symlinked for manual RTP management";
  };
}
