setup_plugin("treesj")
setup_plugin("dial", function(dial)
	local augend = require("dial.augend")
	local manipulate = require("dial.map")
	require("dial.config").augends:register_group({
		default = {
			augend.integer.alias.decimal,
			augend.integer.alias.hex,
			augend.date.alias["%Y/%m/%d"],
			augend.constant.alias.Bool,
			augend.constant.alias.bool,
		},
	})
	map("n", "<C-a>", function()
		manipulate("increment", "normal")
	end)
	map("n", "<C-x>", function()
		manipulate("decrement", "normal")
	end)
	map("n", "g<C-a>", function()
		manipulate("increment", "gnormal")
	end)
	map("n", "g<C-x>", function()
		manipulate("decrement", "gnormal")
	end)
	map("x", "<C-a>", function()
		manipulate("increment", "visual")
	end)
	map("x", "<C-x>", function()
		manipulate("decrement", "visual")
	end)
	map("x", "g<C-a>", function()
		manipulate("increment", "gvisual")
	end)
	map("x", "g<C-x>", function()
		manipulate("decrement", "gvisual")
	end)
end)

utils.packadd("vim-visual-multi", function()
	vim.g.VM_default_mappings = true
end)
setup_plugin("leap")
setup_plugin("flash")
setup_plugin("hop")
setup_plugin("rainbow-delimiters")
setup_plugin("nvim-autopairs")
utils.packadd("vim-sandwich")
setup_plugin("nvim-surround")
utils.packadd("vim-mundo")
setup_plugin("mini.keymap")
setup_plugin("hydra")
setup_plugin("insx")
setup_plugin("which-key")
setup_plugin("indentmini")
utils.packadd("indent-blankline")
setup_plugin("nvim-anydent")
setup_plugin("mini.align")
utils.packadd("tabular")
utils.packadd("nvim-various-textobjs")
setup_plugin("Comment")
utils.packadd("vim-commentary")
